package study.jll.com.greeddao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import study.jll.com.greeddaodemo.Sutdent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SUTDENT".
*/
public class SutdentDao extends AbstractDao<Sutdent, Long> {

    public static final String TABLENAME = "SUTDENT";

    /**
     * Properties of entity Sutdent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uuid = new Property(1, String.class, "uuid", false, "UUID");
        public final static Property WaypointList = new Property(2, String.class, "waypointList", false, "WAYPOINT_LIST");
        public final static Property WaypointStatu = new Property(3, int.class, "waypointStatu", false, "WAYPOINT_STATU");
    }


    public SutdentDao(DaoConfig config) {
        super(config);
    }
    
    public SutdentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SUTDENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UUID\" TEXT UNIQUE ," + // 1: uuid
                "\"WAYPOINT_LIST\" TEXT," + // 2: waypointList
                "\"WAYPOINT_STATU\" INTEGER NOT NULL );"); // 3: waypointStatu
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SUTDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Sutdent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(2, uuid);
        }
 
        String waypointList = entity.getWaypointList();
        if (waypointList != null) {
            stmt.bindString(3, waypointList);
        }
        stmt.bindLong(4, entity.getWaypointStatu());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Sutdent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(2, uuid);
        }
 
        String waypointList = entity.getWaypointList();
        if (waypointList != null) {
            stmt.bindString(3, waypointList);
        }
        stmt.bindLong(4, entity.getWaypointStatu());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Sutdent readEntity(Cursor cursor, int offset) {
        Sutdent entity = new Sutdent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uuid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // waypointList
            cursor.getInt(offset + 3) // waypointStatu
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Sutdent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUuid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWaypointList(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWaypointStatu(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Sutdent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Sutdent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Sutdent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
